name: gstream
description: A Stream Builder Wrapper which aims to deliver a simple, yet powerful context based reactive UI building API.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.6
