name: gstream
description: A Stream Builder Wrapper which aims to deliver a simple, yet powerful context based reactive UI building API.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  uuid: ^3.0.6

dev_dependencies:
   wrg_flutter_lints:
    git:
      url: ssh://git@bitbucket.org/whiterabbitgroup/wrg_flutter_lints.git
      ref: main
